name: Build
on: 
  push:
    branches: ["main"]

jobs:
  build:
    env:
        GONOSUMDB: "github.com/moby/moby"
        GO111MODULE: "on"
    name: Build Application
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.20

    - name: Get dependencies
      run: |
        go get -v -t ./...

    - name: Build
      run: |
        CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o bin/linux/amd64/ping-app

    - uses: actions/upload-artifact@v2
      with:
        name: binaries
        path: |
          ./bin

  release:
    env:
        GONOSUMDB: "github.com/moby/moby"

    name: Release Application
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/download-artifact@v2
      with:
        name: binaries
        path: bin

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Setup Docker Multi-Arch Builder
      run: |
        docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
        docker buildx create --name multi
        docker buildx use multi
        docker buildx inspect --bootstrap

    - name: Build and push Docker
      run: |
        docker buildx build --platform linux/amd64 \
        -t ganeshrockz/ping-app-new:latest \
        -f ./Dockerfile \
        --push